#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* verify API
* verify API documentation
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGResponseEntity
@end

@interface SWGResponseEntity : SWGObject


@property(nonatomic) NSObject* body;

@property(nonatomic) NSString* statusCode;

@property(nonatomic) NSNumber* statusCodeValue;

@end
