#import <Foundation/Foundation.h>
#import "SWGProfileInfoVM.h"
#import "SWGApi.h"

/**
* verify API
* verify API documentation
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGProfileinforesourceApi: NSObject <SWGApi>

extern NSString* kSWGProfileinforesourceApiErrorDomain;
extern NSInteger kSWGProfileinforesourceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// getActiveProfiles
/// 
///
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGProfileInfoVM*
-(NSURLSessionTask*) getActiveProfilesUsingGETWithCompletionHandler: 
    (void (^)(SWGProfileInfoVM* output, NSError* error)) handler;



@end
