#import <Foundation/Foundation.h>
#import "SWGResponseEntity.h"
#import "SWGApi.h"

/**
* verify API
* verify API documentation
*
* OpenAPI spec version: 0.0.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGVerifyresourceApi: NSObject <SWGApi>

extern NSString* kSWGVerifyresourceApiErrorDomain;
extern NSInteger kSWGVerifyresourceApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// charAndNumCode
/// 
///
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return 
-(NSURLSessionTask*) charAndNumCodeUsingGETWithCompletionHandler: 
    (void (^)(NSError* error)) handler;


/// getVerifyCodeByPhone
/// 
///
/// @param phone phone
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSString*
-(NSURLSessionTask*) getVerifyCodeByPhoneUsingGETWithPhone: (NSString*) phone
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;


/// smsCode
/// 
///
/// @param phone phone
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return SWGResponseEntity*
-(NSURLSessionTask*) smsCodeUsingGETWithPhone: (NSString*) phone
    completionHandler: (void (^)(SWGResponseEntity* output, NSError* error)) handler;


/// smsValidate
/// 
///
/// @param phone phone
/// @param smsCode smsCode
/// 
///  code:200 message:"OK",
///  code:401 message:"Unauthorized",
///  code:403 message:"Forbidden",
///  code:404 message:"Not Found"
///
/// @return NSDictionary<NSString*, NSObject*>*
-(NSURLSessionTask*) smsValidateUsingGETWithPhone: (NSString*) phone
    smsCode: (NSString*) smsCode
    completionHandler: (void (^)(NSDictionary<NSString*, NSObject*>* output, NSError* error)) handler;



@end
